/**
 * 20 realistic sample recipes covering all four categories
 * (breakfast, lunch, dinner, pantry) and all food types.
 * Every recipe has English, Telugu and Hindi text for its name,
 * description, ingredients, preparation steps, and benefits.
 *
 * Common staples (salt, water, cooking oil, turmeric) are marked
 * isPantryStaple: true so the "What Can I Cook?" matcher does not
 * unfairly penalize users for not explicitly selecting them.
 */

export const sampleRecipes = [
  {
    name: { en: "Idli", te: "ఇడ్లీ", hi: "इडली" },
    description: {
      en: "Soft, steamed rice and lentil cakes, a classic South Indian breakfast.",
      te: "మెత్తగా ఉండే ఆవిరి మీద ఉడికించిన బియ్యం మరియు పప్పు వంటకం, దక్షిణ భారత అల్పాహారం.",
      hi: "नरम, भाप में पकाए गए चावल और दाल के केक, दक्षिण भारत का लोकप्रिय नाश्ता।",
    },
    category: "breakfast",
    foodType: "vegetarian",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Idli_Sambar.JPG",
    preparationTime: 15,
    cookingTime: 15,
    servings: 2,
    ingredients: [
      { name: { en: "Idli rice", te: "ఇడ్లీ బియ్యం", hi: "इडली चावल" }, quantity: 2, unit: "cup", isPantryStaple: false },
      { name: { en: "Urad dal", te: "మినప్పప్పు", hi: "उड़द दाल" }, quantity: 0.5, unit: "cup", isPantryStaple: false },
      { name: { en: "Salt", te: "ఉప్పు", hi: "नमक" }, quantity: 1, unit: "tsp", isPantryStaple: true },
      { name: { en: "Water", te: "నీరు", hi: "पानी" }, quantity: 2, unit: "cup", isPantryStaple: true },
    ],
    preparationSteps: {
      en: [
        "Soak rice and urad dal separately for 4-6 hours.",
        "Grind both into a smooth, thick batter and mix together.",
        "Leave the batter to ferment overnight.",
        "Add salt and pour into greased idli molds.",
        "Steam for 12-15 minutes until a knife comes out clean.",
      ],
      te: [
        "బియ్యం మరియు మినప్పప్పును విడివిడిగా 4-6 గంటలు నానబెట్టండి.",
        "రెండింటినీ మెత్తగా రుబ్బి కలపండి.",
        "పిండిని రాత్రంతా పులవనివ్వండి.",
        "ఉప్పు కలిపి నూనె రాసిన ఇడ్లీ అచ్చుల్లో పోయండి.",
        "12-15 నిమిషాలు ఆవిరి మీద ఉడికించండి.",
      ],
      hi: [
        "चावल और उड़द दाल को अलग-अलग 4-6 घंटे भिगोएं।",
        "दोनों को बारीक पीसकर मिला लें।",
        "घोल को रात भर खमीर उठने दें।",
        "नमक मिलाकर घी लगे इडली सांचों में डालें।",
        "12-15 मिनट तक भाप में पकाएं।",
      ],
    },
    nutrition: { calories: 150, protein: 4, fat: 0.5, carbohydrates: 30, fiber: 2 },
    benefits: {
      en: ["Low in fat", "Easy to digest", "Good source of energy"],
      te: ["తక్కువ కొవ్వు", "సులభంగా జీర్ణమవుతుంది", "మంచి శక్తి వనరు"],
      hi: ["कम वसा", "आसानी से पचने वाला", "ऊर्जा का अच्छा स्रोत"],
    },
    isPopular: true,
  },
  {
    name: { en: "Masala Dosa", te: "మసాలా దోశ", hi: "मसाला डोसा" },
    description: {
      en: "Crispy rice crepe filled with a spiced potato filling.",
      te: "కారంగా ఉండే ఆలూ కూరతో నింపిన కరకరలాడే బియ్యం దోశ.",
      hi: "मसालेदार आलू भरावन के साथ कुरकुरा चावल का डोसा।",
    },
    category: "breakfast",
    foodType: "vegetarian",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/MasalaDosa.jpg",
    preparationTime: 20,
    cookingTime: 20,
    servings: 2,
    ingredients: [
      { name: { en: "Dosa rice", te: "దోశ బియ్యం", hi: "डोसा चावल" }, quantity: 2, unit: "cup", isPantryStaple: false },
      { name: { en: "Urad dal", te: "మినప్పప్పు", hi: "उड़द दाल" }, quantity: 0.5, unit: "cup", isPantryStaple: false },
      { name: { en: "Potato", te: "బంగాళదుంప", hi: "आलू" }, quantity: 3, unit: "g", isPantryStaple: false },
      { name: { en: "Onion", te: "ఉల్లిపాయ", hi: "प्याज" }, quantity: 1, unit: "g", isPantryStaple: false },
      { name: { en: "Mustard seeds", te: "ఆవాలు", hi: "राई" }, quantity: 1, unit: "tsp", isPantryStaple: false },
      { name: { en: "Turmeric", te: "పసుపు", hi: "हल्दी" }, quantity: 0.5, unit: "tsp", isPantryStaple: true },
      { name: { en: "Cooking oil", te: "వంట నూనె", hi: "खाना पकाने का तेल" }, quantity: 2, unit: "tbsp", isPantryStaple: true },
      { name: { en: "Salt", te: "ఉప్పు", hi: "नमक" }, quantity: 1, unit: "tsp", isPantryStaple: true },
    ],
    preparationSteps: {
      en: [
        "Soak and grind rice and urad dal into a batter, ferment overnight.",
        "Boil and mash the potatoes.",
        "Saute onion, mustard seeds and turmeric, then mix in the mashed potato to make the filling.",
        "Spread a thin layer of batter on a hot griddle.",
        "Add the potato filling, fold, and serve hot.",
      ],
      te: [
        "బియ్యం, మినప్పప్పు నానబెట్టి రుబ్బి రాత్రంతా పులవనివ్వండి.",
        "బంగాళదుంపలను ఉడికించి మెత్తగా చేయండి.",
        "ఉల్లిపాయ, ఆవాలు, పసుపుతో వేపి బంగాళదుంప కలిపి కూర తయారు చేయండి.",
        "వేడి పెనం మీద పలుచగా పిండిని పరచండి.",
        "కూర పెట్టి మడత పెట్టి వేడిగా వడ్డించండి.",
      ],
      hi: [
        "चावल और उड़द दाल भिगोकर पीसें और रात भर खमीर उठने दें।",
        "आलू उबालकर मैश करें।",
        "प्याज, राई और हल्दी भूनकर आलू मिलाएं और भरावन तैयार करें।",
        "गरम तवे पर घोल की पतली परत फैलाएं।",
        "भरावन रखकर मोड़ें और गरमागरम परोसें।",
      ],
    },
    nutrition: { calories: 220, protein: 5, fat: 7, carbohydrates: 35, fiber: 3 },
    benefits: {
      en: ["Provides energy", "Contains dietary fiber", "Good for breakfast"],
      te: ["శక్తినిస్తుంది", "పీచు పదార్థం కలిగి ఉంటుంది", "అల్పాహారానికి మంచిది"],
      hi: ["ऊर्जा प्रदान करता है", "फाइबर से भरपूर", "नाश्ते के लिए अच्छा"],
    },
    isPopular: true,
  },
  {
    name: { en: "Vegetable Upma", te: "కూరగాయల ఉప్మా", hi: "वेजिटेबल उपमा" },
    description: {
      en: "A savory semolina breakfast dish cooked with mixed vegetables.",
      te: "కూరగాయలతో వండిన రవ్వతో చేసిన రుచికరమైన అల్పాహారం.",
      hi: "मिश्रित सब्जियों के साथ पकाया गया स्वादिष्ट सूजी का नाश्ता।",
    },
    category: "breakfast",
    foodType: "vegetarian",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Vegetable_Upma.JPG",
    preparationTime: 10,
    cookingTime: 15,
    servings: 2,
    ingredients: [
      { name: { en: "Rava (semolina)", te: "రవ్వ", hi: "सूजी" }, quantity: 1, unit: "cup", isPantryStaple: false },
      { name: { en: "Carrot", te: "క్యారెట్", hi: "गाजर" }, quantity: 1, unit: "g", isPantryStaple: false },
      { name: { en: "Onion", te: "ఉల్లిపాయ", hi: "प्याज" }, quantity: 1, unit: "g", isPantryStaple: false },
      { name: { en: "Green chilli", te: "పచ్చిమిర్చి", hi: "हरी मिर्च" }, quantity: 2, unit: "g", isPantryStaple: false },
      { name: { en: "Mustard seeds", te: "ఆవాలు", hi: "राई" }, quantity: 1, unit: "tsp", isPantryStaple: false },
      { name: { en: "Cooking oil", te: "వంట నూనె", hi: "खाना पकाने का तेल" }, quantity: 2, unit: "tbsp", isPantryStaple: true },
      { name: { en: "Water", te: "నీరు", hi: "पानी" }, quantity: 2, unit: "cup", isPantryStaple: true },
      { name: { en: "Salt", te: "ఉప్పు", hi: "नमक" }, quantity: 1, unit: "tsp", isPantryStaple: true },
    ],
    preparationSteps: {
      en: [
        "Dry roast the rava until fragrant and set aside.",
        "Heat oil, add mustard seeds, onion, green chilli and carrot.",
        "Add water and salt, bring to a boil.",
        "Slowly stir in the roasted rava, avoiding lumps.",
        "Cook covered for 3-4 minutes and serve hot.",
      ],
      te: [
        "రవ్వను ఎండిగా వేయించి పక్కన పెట్టండి.",
        "నూనె వేడి చేసి ఆవాలు, ఉల్లిపాయ, పచ్చిమిర్చి, క్యారెట్ వేయండి.",
        "నీరు, ఉప్పు వేసి మరిగించండి.",
        "వేయించిన రవ్వను ముద్దలు లేకుండా కలపండి.",
        "మూత పెట్టి 3-4 నిమిషాలు ఉడికించి వడ్డించండి.",
      ],
      hi: [
        "सूजी को खुशबू आने तक भूनकर अलग रख दें।",
        "तेल गरम करें, राई, प्याज, हरी मिर्च और गाजर डालें।",
        "पानी और नमक डालकर उबाल लें।",
        "भुनी सूजी को धीरे-धीरे बिना गांठ बनाए मिलाएं।",
        "ढककर 3-4 मिनट पकाएं और गरमागरम परोसें।",
      ],
    },
    nutrition: { calories: 190, protein: 4, fat: 8, carbohydrates: 26, fiber: 2 },
    benefits: {
      en: ["Quick source of energy", "Light on the stomach", "Contains vegetables' nutrients"],
      te: ["త్వరిత శక్తి వనరు", "కడుపుకు తేలిక", "కూరగాయల పోషకాలు కలిగి ఉంటుంది"],
      hi: ["ऊर्जा का त्वरित स्रोत", "पेट के लिए हल्का", "सब्जियों के पोषक तत्व"],
    },
    isPopular: false,
  },
  {
    name: { en: "Poha", te: "అటుకుల ఉప్మా (పోహా)", hi: "पोहा" },
    description: {
      en: "Flattened rice tossed with onions, peanuts and mild spices.",
      te: "ఉల్లిపాయలు, వేరుశనగలు మరియు తేలికపాటి మసాలాలతో కలిపిన అటుకులు.",
      hi: "प्याज, मूंगफली और हल्के मसालों के साथ बनाया गया चपटा चावल।",
    },
    category: "breakfast",
    foodType: "vegetarian",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Kanda_poha.jpg",
    preparationTime: 10,
    cookingTime: 10,
    servings: 2,
    ingredients: [
      { name: { en: "Flattened rice (poha)", te: "అటుకులు", hi: "पोहा" }, quantity: 2, unit: "cup", isPantryStaple: false },
      { name: { en: "Onion", te: "ఉల్లిపాయ", hi: "प्याज" }, quantity: 1, unit: "g", isPantryStaple: false },
      { name: { en: "Peanuts", te: "వేరుశనగలు", hi: "मूंगफली" }, quantity: 2, unit: "tbsp", isPantryStaple: false },
      { name: { en: "Mustard seeds", te: "ఆవాలు", hi: "राई" }, quantity: 1, unit: "tsp", isPantryStaple: false },
      { name: { en: "Turmeric", te: "పసుపు", hi: "हल्दी" }, quantity: 0.5, unit: "tsp", isPantryStaple: true },
      { name: { en: "Cooking oil", te: "వంట నూనె", hi: "खाना पकाने का तेल" }, quantity: 2, unit: "tbsp", isPantryStaple: true },
      { name: { en: "Salt", te: "ఉప్పు", hi: "नमक" }, quantity: 1, unit: "tsp", isPantryStaple: true },
    ],
    preparationSteps: {
      en: [
        "Rinse the poha in water briefly and drain.",
        "Heat oil, add mustard seeds, peanuts and onion; saute until golden.",
        "Add turmeric and salt.",
        "Add the drained poha and toss gently until heated through.",
        "Garnish with coriander and serve.",
      ],
      te: [
        "అటుకులను నీటిలో వేగంగా కడిగి వడకట్టండి.",
        "నూనె వేడి చేసి ఆవాలు, వేరుశనగలు, ఉల్లిపాయ వేయించండి.",
        "పసుపు, ఉప్పు వేయండి.",
        "అటుకులు వేసి మెత్తగా కలుపుతూ వేడిచేయండి.",
        "కొత్తిమీరతో అలంకరించి వడ్డించండి.",
      ],
      hi: [
        "पोहे को पानी में हल्का धोकर छान लें।",
        "तेल गरम करें, राई, मूंगफली और प्याज डालकर सुनहरा होने तक भूनें।",
        "हल्दी और नमक डालें।",
        "छना हुआ पोहा डालकर धीरे-धीरे मिलाएं।",
        "धनिये से सजाकर परोसें।",
      ],
    },
    nutrition: { calories: 210, protein: 5, fat: 9, carbohydrates: 28, fiber: 2 },
    benefits: {
      en: ["Light and easy to digest", "Good source of carbohydrates", "Contains healthy fats from peanuts"],
      te: ["తేలికగా, సులభంగా జీర్ణమవుతుంది", "మంచి కార్బోహైడ్రేట్ వనరు", "వేరుశనగల నుండి ఆరోగ్యకరమైన కొవ్వులు"],
      hi: ["हल्का और आसानी से पचने वाला", "कार्बोहाइड्रेट का अच्छा स्रोत", "मूंगफली से स्वस्थ वसा"],
    },
    isPopular: false,
  },
  {
    name: { en: "Ven Pongal", te: "వెన్ పొంగలి", hi: "वेन पोंगल" },
    description: {
      en: "A comforting rice and moong dal porridge tempered with pepper and cumin.",
      te: "మిరియాలు, జీలకర్రతో తాలింపు వేసిన బియ్యం, పెసరపప్పు వంటకం.",
      hi: "काली मिर्च और जीरे से तड़का लगाया गया चावल और मूंग दाल की खिचड़ी।",
    },
    category: "breakfast",
    foodType: "vegetarian",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Venpongal.jpg",
    preparationTime: 10,
    cookingTime: 20,
    servings: 2,
    ingredients: [
      { name: { en: "Rice", te: "బియ్యం", hi: "चावल" }, quantity: 1, unit: "cup", isPantryStaple: false },
      { name: { en: "Moong dal", te: "పెసరపప్పు", hi: "मूंग दाल" }, quantity: 0.5, unit: "cup", isPantryStaple: false },
      { name: { en: "Black pepper", te: "మిరియాలు", hi: "काली मिर्च" }, quantity: 1, unit: "tsp", isPantryStaple: false },
      { name: { en: "Cumin seeds", te: "జీలకర్ర", hi: "जीरा" }, quantity: 1, unit: "tsp", isPantryStaple: false },
      { name: { en: "Ghee", te: "నెయ్యి", hi: "घी" }, quantity: 2, unit: "tbsp", isPantryStaple: true },
      { name: { en: "Water", te: "నీరు", hi: "पानी" }, quantity: 4, unit: "cup", isPantryStaple: true },
      { name: { en: "Salt", te: "ఉప్పు", hi: "नमक" }, quantity: 1, unit: "tsp", isPantryStaple: true },
    ],
    preparationSteps: {
      en: [
        "Dry roast rice and moong dal lightly.",
        "Pressure cook with water and salt until soft and mushy.",
        "In a separate pan, heat ghee and temper with pepper and cumin.",
        "Pour the tempering over the cooked rice-dal mixture and mix well.",
        "Serve hot with chutney or sambar.",
      ],
      te: [
        "బియ్యం, పెసరపప్పు తేలికగా వేయించండి.",
        "నీరు, ఉప్పుతో మెత్తగా అయ్యేవరకు ప్రెజర్ కుక్ చేయండి.",
        "వేరే పాత్రలో నెయ్యి వేడి చేసి మిరియాలు, జీలకర్రతో తాలింపు వేయండి.",
        "తాలింపును ఉడికిన మిశ్రమంపై పోసి బాగా కలపండి.",
        "చట్నీ లేదా సాంబార్‌తో వేడిగా వడ్డించండి.",
      ],
      hi: [
        "चावल और मूंग दाल को हल्का भून लें।",
        "पानी और नमक के साथ नरम होने तक प्रेशर कुक करें।",
        "अलग पैन में घी गरम कर काली मिर्च और जीरे का तड़का लगाएं।",
        "तड़के को पके हुए मिश्रण पर डालकर अच्छी तरह मिलाएं।",
        "चटनी या सांबार के साथ गरमागरम परोसें।",
      ],
    },
    nutrition: { calories: 260, protein: 7, fat: 9, carbohydrates: 38, fiber: 3 },
    benefits: {
      en: ["Good source of protein", "Easy to digest", "Comforting and filling"],
      te: ["మంచి ప్రొటీన్ వనరు", "సులభంగా జీర్ణమవుతుంది", "తృప్తినిచ్చే ఆహారం"],
      hi: ["प्रोटीन का अच्छा स्रोत", "आसानी से पचने वाला", "पेट भरने वाला और आरामदायक"],
    },
    isPopular: false,
  },
  {
    name: { en: "Aloo Paratha", te: "ఆలూ పరాఠా", hi: "आलू पराठा" },
    description: {
      en: "Whole wheat flatbread stuffed with spiced mashed potato.",
      te: "మసాలా వేసిన బంగాళదుంపతో నింపిన గోధుమ రొట్టె.",
      hi: "मसालेदार आलू भरावन के साथ बनाई गई गेहूं की रोटी।",
    },
    category: "breakfast",
    foodType: "vegetarian",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Aloo_Paratha_with_Butter_from_India.jpg",
    preparationTime: 20,
    cookingTime: 15,
    servings: 2,
    ingredients: [
      { name: { en: "Wheat flour", te: "గోధుమ పిండి", hi: "गेहूं का आटा" }, quantity: 2, unit: "cup", isPantryStaple: false },
      { name: { en: "Potato", te: "బంగాళదుంప", hi: "आलू" }, quantity: 3, unit: "g", isPantryStaple: false },
      { name: { en: "Green chilli", te: "పచ్చిమిర్చి", hi: "हरी मिर्च" }, quantity: 2, unit: "g", isPantryStaple: false },
      { name: { en: "Chilli powder", te: "మిర్చి పొడి", hi: "मिर्च पाउडर" }, quantity: 0.5, unit: "tsp", isPantryStaple: false },
      { name: { en: "Cooking oil", te: "వంట నూనె", hi: "खाना पकाने का तेल" }, quantity: 3, unit: "tbsp", isPantryStaple: true },
      { name: { en: "Salt", te: "ఉప్పు", hi: "नमक" }, quantity: 1, unit: "tsp", isPantryStaple: true },
    ],
    preparationSteps: {
      en: [
        "Knead the wheat flour into a soft dough and rest for 15 minutes.",
        "Boil, peel and mash the potatoes; mix with chilli, chilli powder and salt.",
        "Divide dough into balls, stuff with the potato filling and roll gently.",
        "Cook on a hot griddle with oil until golden brown on both sides.",
        "Serve hot with curd or pickle.",
      ],
      te: [
        "గోధుమ పిండిని మెత్తగా కలిపి 15 నిమిషాలు నానబెట్టండి.",
        "బంగాళదుంపలు ఉడికించి, తొక్క తీసి మెత్తగా చేసి, మిర్చి, మిర్చి పొడి, ఉప్పు కలపండి.",
        "పిండిని ఉండలుగా చేసి కూర నింపి మెత్తగా ఒత్తండి.",
        "వేడి పెనం మీద నూనెతో రెండు వైపులా బంగారు రంగు వచ్చేవరకు కాల్చండి.",
        "పెరుగు లేదా ఊరగాయతో వేడిగా వడ్డించండి.",
      ],
      hi: [
        "गेहूं के आटे को नरम गूंथकर 15 मिनट के लिए रख दें।",
        "आलू उबालकर, छीलकर मैश करें और मिर्च, मिर्च पाउडर, नमक मिलाएं।",
        "आटे की लोइयां बनाकर भरावन भरें और धीरे से बेलें।",
        "गरम तवे पर तेल लगाकर दोनों तरफ सुनहरा होने तक सेंकें।",
        "दही या अचार के साथ गरमागरम परोसें।",
      ],
    },
    nutrition: { calories: 320, protein: 7, fat: 12, carbohydrates: 45, fiber: 4 },
    benefits: {
      en: ["Filling and energizing", "Contains dietary fiber", "Good for a hearty breakfast"],
      te: ["తృప్తినిచ్చి శక్తినిస్తుంది", "పీచు పదార్థం కలిగి ఉంటుంది", "పుష్టికరమైన అల్పాహారానికి మంచిది"],
      hi: ["पेट भरने वाला और ऊर्जावान", "फाइबर से भरपूर", "भरपूर नाश्ते के लिए अच्छा"],
    },
    isPopular: true,
  },
  {
    name: { en: "Tomato Rice", te: "టమాటా అన్నం", hi: "टमाटर चावल" },
    description: {
      en: "Tangy, mildly spiced rice cooked with fresh tomatoes.",
      te: "తాజా టమాటాలతో వండిన కారంగా, పులుపుగా ఉండే అన్నం.",
      hi: "ताज़े टमाटर के साथ पकाया गया खट्टा-मसालेदार चावल।",
    },
    category: "lunch",
    foodType: "vegetarian",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Tomato_Rice_%26_Onion_Raitha.JPG",
    preparationTime: 10,
    cookingTime: 20,
    servings: 2,
    ingredients: [
      { name: { en: "Rice", te: "బియ్యం", hi: "चावल" }, quantity: 1, unit: "cup", isPantryStaple: false },
      { name: { en: "Tomato", te: "టమాటా", hi: "टमाटर" }, quantity: 3, unit: "g", isPantryStaple: false },
      { name: { en: "Onion", te: "ఉల్లిపాయ", hi: "प्याज" }, quantity: 1, unit: "g", isPantryStaple: false },
      { name: { en: "Green chilli", te: "పచ్చిమిర్చి", hi: "हरी मिर्च" }, quantity: 2, unit: "g", isPantryStaple: false },
      { name: { en: "Turmeric", te: "పసుపు", hi: "हल्दी" }, quantity: 0.5, unit: "tsp", isPantryStaple: true },
      { name: { en: "Cooking oil", te: "వంట నూనె", hi: "खाना पकाने का तेल" }, quantity: 2, unit: "tbsp", isPantryStaple: true },
      { name: { en: "Salt", te: "ఉప్పు", hi: "नमक" }, quantity: 1, unit: "tsp", isPantryStaple: true },
    ],
    preparationSteps: {
      en: [
        "Cook the rice and let it cool.",
        "Heat oil, saute onion and green chilli until translucent.",
        "Add chopped tomatoes and turmeric, cook until soft and pulpy.",
        "Add salt and mix in the cooked rice gently.",
        "Cook for 2-3 minutes on low heat and serve.",
      ],
      te: [
        "అన్నం వండి చల్లారనివ్వండి.",
        "నూనె వేడి చేసి ఉల్లిపాయ, పచ్చిమిర్చి వేయించండి.",
        "టమాటా ముక్కలు, పసుపు వేసి మెత్తగా అయ్యేవరకు ఉడికించండి.",
        "ఉప్పు వేసి వండిన అన్నం మెత్తగా కలపండి.",
        "తక్కువ మంటపై 2-3 నిమిషాలు ఉడికించి వడ్డించండి.",
      ],
      hi: [
        "चावल पकाकर ठंडा होने दें।",
        "तेल गरम करें, प्याज और हरी मिर्च भूनें।",
        "कटे टमाटर और हल्दी डालकर नरम होने तक पकाएं।",
        "नमक डालकर पके चावल धीरे से मिलाएं।",
        "धीमी आंच पर 2-3 मिनट पकाकर परोसें।",
      ],
    },
    nutrition: { calories: 300, protein: 5, fat: 8, carbohydrates: 50, fiber: 3 },
    benefits: {
      en: ["Rich in vitamin C", "Provides quick energy", "Contains antioxidants from tomato"],
      te: ["విటమిన్ సి సమృద్ధిగా ఉంటుంది", "త్వరిత శక్తినిస్తుంది", "టమాటా నుండి యాంటీఆక్సిడెంట్లు"],
      hi: ["विटामिन सी से भरपूर", "त्वरित ऊर्जा प्रदान करता है", "टमाटर से एंटीऑक्सीडेंट"],
    },
    isPopular: true,
  },
  {
    name: { en: "Sambar Rice", te: "సాంబార్ అన్నం", hi: "सांबर चावल" },
    description: {
      en: "Rice mixed with a tangy, protein-rich lentil and vegetable stew.",
      te: "పులుపు, ప్రొటీన్ సమృద్ధిగా ఉండే పప్పు కూరతో కలిపిన అన్నం.",
      hi: "खट्टी, प्रोटीन युक्त दाल-सब्जी करी के साथ मिला हुआ चावल।",
    },
    category: "lunch",
    foodType: "vegetarian",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Sambar_Rice.jpg",
    preparationTime: 15,
    cookingTime: 25,
    servings: 3,
    ingredients: [
      { name: { en: "Rice", te: "బియ్యం", hi: "चावल" }, quantity: 1, unit: "cup", isPantryStaple: false },
      { name: { en: "Toor dal", te: "కంది పప్పు", hi: "तूर दाल" }, quantity: 0.5, unit: "cup", isPantryStaple: false },
      { name: { en: "Drumstick", te: "మునగకాయ", hi: "सहजन" }, quantity: 1, unit: "g", isPantryStaple: false },
      { name: { en: "Tamarind", te: "చింతపండు", hi: "इमली" }, quantity: 1, unit: "tbsp", isPantryStaple: false },
      { name: { en: "Sambar powder", te: "సాంబార్ పొడి", hi: "सांबर मसाला" }, quantity: 2, unit: "tsp", isPantryStaple: false },
      { name: { en: "Turmeric", te: "పసుపు", hi: "हल्दी" }, quantity: 0.5, unit: "tsp", isPantryStaple: true },
      { name: { en: "Cooking oil", te: "వంట నూనె", hi: "खाना पकाने का तेल" }, quantity: 1, unit: "tbsp", isPantryStaple: true },
      { name: { en: "Salt", te: "ఉప్పు", hi: "नमक" }, quantity: 1, unit: "tsp", isPantryStaple: true },
    ],
    preparationSteps: {
      en: [
        "Cook rice separately and set aside.",
        "Pressure cook toor dal with turmeric until soft.",
        "Boil drumstick with tamarind water and sambar powder.",
        "Add the cooked dal and salt, simmer for 10 minutes.",
        "Mix the sambar with rice and serve hot.",
      ],
      te: [
        "అన్నం వేరుగా వండి పక్కన పెట్టండి.",
        "కంది పప్పును పసుపుతో మెత్తగా అయ్యేవరకు ప్రెజర్ కుక్ చేయండి.",
        "మునగకాయను చింతపండు నీటితో, సాంబార్ పొడితో ఉడికించండి.",
        "వండిన పప్పు, ఉప్పు వేసి 10 నిమిషాలు ఉడికించండి.",
        "సాంబార్‌ను అన్నంతో కలిపి వేడిగా వడ్డించండి.",
      ],
      hi: [
        "चावल अलग से पकाकर रख दें।",
        "तूर दाल को हल्दी के साथ नरम होने तक प्रेशर कुक करें।",
        "सहजन को इमली के पानी और सांबर मसाले के साथ उबालें।",
        "पकी दाल और नमक डालकर 10 मिनट पकाएं।",
        "सांबर को चावल में मिलाकर गरमागरम परोसें।",
      ],
    },
    nutrition: { calories: 340, protein: 10, fat: 6, carbohydrates: 58, fiber: 6 },
    benefits: {
      en: ["Good source of protein", "Contains dietary fiber", "Provides essential vitamins from vegetables"],
      te: ["మంచి ప్రొటీన్ వనరు", "పీచు పదార్థం కలిగి ఉంటుంది", "కూరగాయల నుండి విటమిన్లు"],
      hi: ["प्रोटीन का अच्छा स्रोत", "फाइबर से भरपूर", "सब्जियों से आवश्यक विटामिन"],
    },
    isPopular: true,
  },
  {
    name: { en: "Dal Tadka", te: "పప్పు తాలింపు", hi: "दाल तड़का" },
    description: {
      en: "Yellow lentils simmered and finished with a fragrant ghee tempering.",
      te: "ఉడికించిన కంది పప్పుకు నెయ్యి తాలింపు వేసిన వంటకం.",
      hi: "पकी हुई दाल पर घी के सुगंधित तड़के से तैयार व्यंजन।",
    },
    category: "lunch",
    foodType: "vegetarian",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Dal_tadka_Picture.JPG",
    preparationTime: 10,
    cookingTime: 20,
    servings: 3,
    ingredients: [
      { name: { en: "Toor dal", te: "కంది పప్పు", hi: "तूर दाल" }, quantity: 1, unit: "cup", isPantryStaple: false },
      { name: { en: "Tomato", te: "టమాటా", hi: "टमाटर" }, quantity: 1, unit: "g", isPantryStaple: false },
      { name: { en: "Garlic", te: "వెల్లుల్లి", hi: "लहसुन" }, quantity: 4, unit: "g", isPantryStaple: false },
      { name: { en: "Cumin seeds", te: "జీలకర్ర", hi: "जीरा" }, quantity: 1, unit: "tsp", isPantryStaple: false },
      { name: { en: "Turmeric", te: "పసుపు", hi: "हल्दी" }, quantity: 0.5, unit: "tsp", isPantryStaple: true },
      { name: { en: "Ghee", te: "నెయ్యి", hi: "घी" }, quantity: 2, unit: "tbsp", isPantryStaple: true },
      { name: { en: "Salt", te: "ఉప్పు", hi: "नमक" }, quantity: 1, unit: "tsp", isPantryStaple: true },
    ],
    preparationSteps: {
      en: [
        "Pressure cook the dal with turmeric and salt until soft.",
        "Mash the cooked dal lightly and set aside.",
        "Heat ghee, add cumin seeds and garlic, saute until golden.",
        "Add chopped tomato and cook until soft.",
        "Pour the tempering over the dal, mix and simmer for 5 minutes.",
      ],
      te: [
        "పప్పును పసుపు, ఉప్పుతో మెత్తగా అయ్యేవరకు ప్రెజర్ కుక్ చేయండి.",
        "ఉడికిన పప్పును కొద్దిగా నలగ్గొట్టి పక్కన పెట్టండి.",
        "నెయ్యి వేడి చేసి జీలకర్ర, వెల్లుల్లి బంగారు రంగు వచ్చేవరకు వేయించండి.",
        "టమాటా ముక్కలు వేసి మెత్తగా అయ్యేవరకు ఉడికించండి.",
        "తాలింపును పప్పుపై పోసి కలిపి 5 నిమిషాలు ఉడికించండి.",
      ],
      hi: [
        "दाल को हल्दी और नमक के साथ नरम होने तक प्रेशर कुक करें।",
        "पकी दाल को हल्का मैश करके अलग रख दें।",
        "घी गरम कर जीरा और लहसुन सुनहरा होने तक भूनें।",
        "कटे टमाटर डालकर नरम होने तक पकाएं।",
        "तड़के को दाल पर डालकर मिलाएं और 5 मिनट पकाएं।",
      ],
    },
    nutrition: { calories: 220, protein: 12, fat: 8, carbohydrates: 28, fiber: 7 },
    benefits: {
      en: ["Excellent source of protein", "High in dietary fiber", "Supports a balanced diet"],
      te: ["అద్భుతమైన ప్రొటీన్ వనరు", "అధిక పీచు పదార్థం", "సమతుల్య ఆహారానికి తోడ్పడుతుంది"],
      hi: ["प्रोटीन का उत्कृष्ट स्रोत", "उच्च फाइबर युक्त", "संतुलित आहार में सहायक"],
    },
    isPopular: false,
  },
  {
    name: { en: "Mixed Vegetable Curry", te: "కూరగాయల కూర", hi: "मिक्स वेजिटेबल करी" },
    description: {
      en: "A wholesome curry made with seasonal mixed vegetables in a mild masala.",
      te: "కాలానుగుణ కూరగాయలతో తేలికపాటి మసాలాతో వండిన కూర.",
      hi: "मौसमी मिश्रित सब्जियों से हल्के मसाले में बनी करी।",
    },
    category: "lunch",
    foodType: "vegetarian",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Vegetarian_Curry.jpeg",
    preparationTime: 15,
    cookingTime: 20,
    servings: 3,
    ingredients: [
      { name: { en: "Carrot", te: "క్యారెట్", hi: "गाजर" }, quantity: 1, unit: "g", isPantryStaple: false },
      { name: { en: "Beans", te: "బీన్స్", hi: "बीन्स" }, quantity: 1, unit: "g", isPantryStaple: false },
      { name: { en: "Potato", te: "బంగాళదుంప", hi: "आलू" }, quantity: 2, unit: "g", isPantryStaple: false },
      { name: { en: "Onion", te: "ఉల్లిపాయ", hi: "प्याज" }, quantity: 1, unit: "g", isPantryStaple: false },
      { name: { en: "Tomato", te: "టమాటా", hi: "टमाटर" }, quantity: 1, unit: "g", isPantryStaple: false },
      { name: { en: "Turmeric", te: "పసుపు", hi: "हल्दी" }, quantity: 0.5, unit: "tsp", isPantryStaple: true },
      { name: { en: "Cooking oil", te: "వంట నూనె", hi: "खाना पकाने का तेल" }, quantity: 2, unit: "tbsp", isPantryStaple: true },
      { name: { en: "Salt", te: "ఉప్పు", hi: "नमक" }, quantity: 1, unit: "tsp", isPantryStaple: true },
    ],
    preparationSteps: {
      en: [
        "Chop all vegetables into bite-sized pieces.",
        "Heat oil, saute onion until translucent.",
        "Add tomato and turmeric, cook until soft.",
        "Add the vegetables, salt and a little water, cover and cook until tender.",
        "Serve hot with rice or roti.",
      ],
      te: [
        "అన్ని కూరగాయలను చిన్న ముక్కలుగా కోయండి.",
        "నూనె వేడి చేసి ఉల్లిపాయ వేయించండి.",
        "టమాటా, పసుపు వేసి మెత్తగా అయ్యేవరకు ఉడికించండి.",
        "కూరగాయలు, ఉప్పు, కొద్దిగా నీరు వేసి మూత పెట్టి మెత్తగా అయ్యేవరకు ఉడికించండి.",
        "అన్నం లేదా రొట్టెతో వేడిగా వడ్డించండి.",
      ],
      hi: [
        "सभी सब्जियों को छोटे टुकड़ों में काटें।",
        "तेल गरम कर प्याज भूनें।",
        "टमाटर और हल्दी डालकर नरम होने तक पकाएं।",
        "सब्जियां, नमक और थोड़ा पानी डालकर ढककर नरम होने तक पकाएं।",
        "चावल या रोटी के साथ गरमागरम परोसें।",
      ],
    },
    nutrition: { calories: 180, protein: 4, fat: 7, carbohydrates: 26, fiber: 6 },
    benefits: {
      en: ["Rich in vitamins and minerals", "Contains dietary fiber", "Supports a balanced diet"],
      te: ["విటమిన్లు, ఖనిజాలు సమృద్ధిగా ఉంటాయి", "పీచు పదార్థం కలిగి ఉంటుంది", "సమతుల్య ఆహారానికి తోడ్పడుతుంది"],
      hi: ["विटामिन और खनिजों से भरपूर", "फाइबर युक्त", "संतुलित आहार में सहायक"],
    },
    isPopular: false,
  },
  {
    name: { en: "Chicken Curry", te: "చికెన్ కూర", hi: "चिकन करी" },
    description: {
      en: "Classic home-style chicken curry simmered in an onion-tomato masala.",
      te: "ఉల్లిపాయ-టమాటా మసాలాలో ఉడికించిన సంప్రదాయ చికెన్ కూర.",
      hi: "प्याज-टमाटर मसाले में पकाई गई पारंपरिक घरेलू चिकन करी।",
    },
    category: "lunch",
    foodType: "non-vegetarian",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Chicken_curry.jpg",
    preparationTime: 15,
    cookingTime: 35,
    servings: 3,
    ingredients: [
      { name: { en: "Chicken", te: "చికెన్", hi: "चिकन" }, quantity: 500, unit: "g", isPantryStaple: false },
      { name: { en: "Onion", te: "ఉల్లిపాయ", hi: "प्याज" }, quantity: 2, unit: "g", isPantryStaple: false },
      { name: { en: "Tomato", te: "టమాటా", hi: "टमाटर" }, quantity: 2, unit: "g", isPantryStaple: false },
      { name: { en: "Ginger garlic paste", te: "అల్లం వెల్లుల్లి పేస్ట్", hi: "अदरक लहसुन पेस्ट" }, quantity: 1, unit: "tbsp", isPantryStaple: false },
      { name: { en: "Chilli powder", te: "మిర్చి పొడి", hi: "मिर्च पाउडर" }, quantity: 1, unit: "tsp", isPantryStaple: false },
      { name: { en: "Garam masala", te: "గరం మసాలా", hi: "गरम मसाला" }, quantity: 1, unit: "tsp", isPantryStaple: false },
      { name: { en: "Turmeric", te: "పసుపు", hi: "हल्दी" }, quantity: 0.5, unit: "tsp", isPantryStaple: true },
      { name: { en: "Cooking oil", te: "వంట నూనె", hi: "खाना पकाने का तेल" }, quantity: 3, unit: "tbsp", isPantryStaple: true },
      { name: { en: "Salt", te: "ఉప్పు", hi: "नमक" }, quantity: 1, unit: "tsp", isPantryStaple: true },
    ],
    preparationSteps: {
      en: [
        "Heat oil and saute onions until golden brown.",
        "Add ginger garlic paste and cook until the raw smell disappears.",
        "Add tomatoes, turmeric and chilli powder, cook until oil separates.",
        "Add chicken pieces and salt, cook until the chicken is sealed.",
        "Add water, cover and simmer for 20 minutes; finish with garam masala.",
      ],
      te: [
        "నూనె వేడి చేసి ఉల్లిపాయలు బంగారు రంగు వచ్చేవరకు వేయించండి.",
        "అల్లం వెల్లుల్లి పేస్ట్ వేసి ముడి వాసన పోయేవరకు వేయించండి.",
        "టమాటాలు, పసుపు, మిర్చి పొడి వేసి నూనె విడిపోయేవరకు ఉడికించండి.",
        "చికెన్ ముక్కలు, ఉప్పు వేసి బాగా కలుపుతూ ఉడికించండి.",
        "నీరు వేసి మూత పెట్టి 20 నిమిషాలు ఉడికించి, గరం మసాలా వేసి పూర్తి చేయండి.",
      ],
      hi: [
        "तेल गरम कर प्याज सुनहरा होने तक भूनें।",
        "अदरक लहसुन पेस्ट डालकर कच्ची महक जाने तक पकाएं।",
        "टमाटर, हल्दी और मिर्च पाउडर डालकर तेल अलग होने तक पकाएं।",
        "चिकन के टुकड़े और नमक डालकर सील होने तक पकाएं।",
        "पानी डालकर ढककर 20 मिनट पकाएं और गरम मसाला डालकर पूरा करें।",
      ],
    },
    nutrition: { calories: 380, protein: 28, fat: 22, carbohydrates: 10, fiber: 2 },
    benefits: {
      en: ["Excellent source of protein", "Supports muscle health", "Contains essential nutrients"],
      te: ["అద్భుతమైన ప్రొటీన్ వనరు", "కండరాల ఆరోగ్యానికి తోడ్పడుతుంది", "అవసరమైన పోషకాలు కలిగి ఉంటుంది"],
      hi: ["प्रोटीन का उत्कृष्ट स्रोत", "मांसपेशियों के स्वास्थ्य में सहायक", "आवश्यक पोषक तत्व"],
    },
    isPopular: true,
  },
  {
    name: { en: "Paneer Butter Masala", te: "పన్నీర్ బటర్ మసాలా", hi: "पनीर बटर मसाला" },
    description: {
      en: "Soft paneer cubes in a rich, creamy tomato-based gravy.",
      te: "మెత్తని పన్నీర్ ముక్కలతో గొప్ప క్రీమీ టమాటా గ్రేవీ.",
      hi: "समृद्ध, मलाईदार टमाटर आधारित ग्रेवी में नरम पनीर के टुकड़े।",
    },
    category: "lunch",
    foodType: "vegetarian",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Paneer_Butter_Masala.jpg",
    preparationTime: 15,
    cookingTime: 25,
    servings: 3,
    ingredients: [
      { name: { en: "Paneer", te: "పన్నీర్", hi: "पनीर" }, quantity: 250, unit: "g", isPantryStaple: false },
      { name: { en: "Tomato", te: "టమాటా", hi: "टमाटर" }, quantity: 3, unit: "g", isPantryStaple: false },
      { name: { en: "Cashew nuts", te: "జీడిపప్పు", hi: "काजू" }, quantity: 10, unit: "g", isPantryStaple: false },
      { name: { en: "Butter", te: "వెన్న", hi: "मक्खन" }, quantity: 2, unit: "tbsp", isPantryStaple: false },
      { name: { en: "Cream", te: "క్రీమ్", hi: "क्रीम" }, quantity: 2, unit: "tbsp", isPantryStaple: false },
      { name: { en: "Garam masala", te: "గరం మసాలా", hi: "गरम मसाला" }, quantity: 1, unit: "tsp", isPantryStaple: false },
      { name: { en: "Salt", te: "ఉప్పు", hi: "नमक" }, quantity: 1, unit: "tsp", isPantryStaple: true },
    ],
    preparationSteps: {
      en: [
        "Blanch tomatoes and cashews, then blend into a smooth puree.",
        "Melt butter in a pan and cook the puree until it thickens.",
        "Add garam masala and salt, simmer for 5 minutes.",
        "Add paneer cubes and cook gently for 3-4 minutes.",
        "Finish with cream and serve hot with naan or rice.",
      ],
      te: [
        "టమాటాలు, జీడిపప్పు ఉడికించి మెత్తగా రుబ్బండి.",
        "వెన్న వేడి చేసి రుబ్బిన మిశ్రమాన్ని చిక్కగా అయ్యేవరకు ఉడికించండి.",
        "గరం మసాలా, ఉప్పు వేసి 5 నిమిషాలు ఉడికించండి.",
        "పన్నీర్ ముక్కలు వేసి 3-4 నిమిషాలు మెత్తగా ఉడికించండి.",
        "క్రీమ్ వేసి నాన్ లేదా అన్నంతో వేడిగా వడ్డించండి.",
      ],
      hi: [
        "टमाटर और काजू को उबालकर बारीक पीस लें।",
        "मक्खन गरम कर प्यूरी को गाढ़ा होने तक पकाएं।",
        "गरम मसाला और नमक डालकर 5 मिनट पकाएं।",
        "पनीर के टुकड़े डालकर धीरे से 3-4 मिनट पकाएं।",
        "क्रीम डालकर नान या चावल के साथ गरमागरम परोसें।",
      ],
    },
    nutrition: { calories: 420, protein: 16, fat: 32, carbohydrates: 18, fiber: 3 },
    benefits: {
      en: ["Good source of protein and calcium", "Provides energy", "Rich and satisfying"],
      te: ["ప్రొటీన్, కాల్షియం మంచి వనరు", "శక్తినిస్తుంది", "సంతృప్తినిచ్చేది"],
      hi: ["प्रोटीन और कैल्शियम का अच्छा स्रोत", "ऊर्जा प्रदान करता है", "समृद्ध और संतोषजनक"],
    },
    isPopular: true,
  },
  {
    name: { en: "Chicken Biryani", te: "చికెన్ బిర్యానీ", hi: "चिकन बिरयानी" },
    description: {
      en: "Fragrant basmati rice layered and slow-cooked with spiced chicken.",
      te: "మసాలా చికెన్‌తో పొరలుగా వేసి నెమ్మదిగా ఉడికించిన సుగంధ బాస్మతి బియ్యం.",
      hi: "मसालेदार चिकन के साथ परतों में धीमी आंच पर पकाए गए सुगंधित बासमती चावल।",
    },
    category: "lunch",
    foodType: "non-vegetarian",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Hyderabadi_Chicken_Biryani.jpg",
    preparationTime: 30,
    cookingTime: 45,
    servings: 4,
    ingredients: [
      { name: { en: "Basmati rice", te: "బాస్మతి బియ్యం", hi: "बासमती चावल" }, quantity: 2, unit: "cup", isPantryStaple: false },
      { name: { en: "Chicken", te: "చికెన్", hi: "चिकन" }, quantity: 500, unit: "g", isPantryStaple: false },
      { name: { en: "Onion", te: "ఉల్లిపాయ", hi: "प्याज" }, quantity: 2, unit: "g", isPantryStaple: false },
      { name: { en: "Curd", te: "పెరుగు", hi: "दही" }, quantity: 0.5, unit: "cup", isPantryStaple: false },
      { name: { en: "Biryani masala", te: "బిర్యానీ మసాలా", hi: "बिरयानी मसाला" }, quantity: 2, unit: "tbsp", isPantryStaple: false },
      { name: { en: "Mint leaves", te: "పుదీనా ఆకులు", hi: "पुदीने के पत्ते" }, quantity: 1, unit: "g", isPantryStaple: false },
      { name: { en: "Cooking oil", te: "వంట నూనె", hi: "खाना पकाने का तेल" }, quantity: 3, unit: "tbsp", isPantryStaple: true },
      { name: { en: "Salt", te: "ఉప్పు", hi: "नमक" }, quantity: 1, unit: "tsp", isPantryStaple: true },
    ],
    preparationSteps: {
      en: [
        "Marinate chicken with curd, biryani masala and salt for 30 minutes.",
        "Parboil the basmati rice with whole spices until 70% cooked.",
        "Fry onions until golden and cook the marinated chicken until nearly done.",
        "Layer the rice over the chicken, top with fried onion and mint.",
        "Cover tightly and cook on low heat (dum) for 20 minutes before serving.",
      ],
      te: [
        "చికెన్‌ను పెరుగు, బిర్యానీ మసాలా, ఉప్పుతో 30 నిమిషాలు మెరినేట్ చేయండి.",
        "బాస్మతి బియ్యాన్ని పూర్తి మసాలాలతో 70% ఉడికేవరకు ఉడికించండి.",
        "ఉల్లిపాయలు బంగారు రంగు వచ్చేవరకు వేయించి మెరినేట్ చేసిన చికెన్ దాదాపు ఉడికేవరకు వండండి.",
        "చికెన్ పైన బియ్యం పొరగా వేసి, వేయించిన ఉల్లిపాయ, పుదీనా వేయండి.",
        "గట్టిగా మూత పెట్టి తక్కువ మంటపై (దమ్) 20 నిమిషాలు ఉడికించి వడ్డించండి.",
      ],
      hi: [
        "चिकन को दही, बिरयानी मसाला और नमक के साथ 30 मिनट मैरिनेट करें।",
        "बासमती चावल को साबुत मसालों के साथ 70% पकने तक उबालें।",
        "प्याज को सुनहरा तलें और मैरिनेट किए चिकन को लगभग पकने तक पकाएं।",
        "चिकन के ऊपर चावल की परत बिछाएं, ऊपर तला प्याज और पुदीना डालें।",
        "कसकर ढककर धीमी आंच पर (दम) 20 मिनट पकाकर परोसें।",
      ],
    },
    nutrition: { calories: 480, protein: 26, fat: 18, carbohydrates: 55, fiber: 3 },
    benefits: {
      en: ["Good source of protein", "Provides energy", "A complete, satisfying meal"],
      te: ["మంచి ప్రొటీన్ వనరు", "శక్తినిస్తుంది", "పూర్తి, సంతృప్తినిచ్చే భోజనం"],
      hi: ["प्रोटीन का अच्छा स्रोत", "ऊर्जा प्रदान करता है", "एक संपूर्ण, संतोषजनक भोजन"],
    },
    isPopular: true,
  },
  {
    name: { en: "Roti with Butter", te: "వెన్న రొట్టె", hi: "मक्खन रोटी" },
    description: {
      en: "Soft whole wheat flatbread brushed with butter, a staple dinner bread.",
      te: "వెన్న రాసిన మెత్తని గోధుమ రొట్టె, రాత్రి భోజనానికి ప్రధాన ఆహారం.",
      hi: "मक्खन लगी नरम गेहूं की रोटी, रात के खाने की मुख्य रोटी।",
    },
    category: "dinner",
    foodType: "vegetarian",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Chapati_2.jpg",
    preparationTime: 15,
    cookingTime: 15,
    servings: 2,
    ingredients: [
      { name: { en: "Wheat flour", te: "గోధుమ పిండి", hi: "गेहूं का आटा" }, quantity: 2, unit: "cup", isPantryStaple: false },
      { name: { en: "Butter", te: "వెన్న", hi: "मक्खन" }, quantity: 2, unit: "tbsp", isPantryStaple: false },
      { name: { en: "Water", te: "నీరు", hi: "पानी" }, quantity: 1, unit: "cup", isPantryStaple: true },
      { name: { en: "Salt", te: "ఉప్పు", hi: "नमक" }, quantity: 0.5, unit: "tsp", isPantryStaple: true },
    ],
    preparationSteps: {
      en: [
        "Knead the flour with water and salt into a soft dough.",
        "Rest the dough for 15 minutes.",
        "Divide into balls and roll out thin discs.",
        "Cook each roti on a hot griddle until light brown spots appear on both sides.",
        "Brush with butter and serve hot.",
      ],
      te: [
        "పిండిని నీరు, ఉప్పుతో మెత్తగా కలపండి.",
        "పిండిని 15 నిమిషాలు నానబెట్టండి.",
        "ఉండలుగా చేసి పలుచగా ఒత్తండి.",
        "వేడి పెనం మీద రెండు వైపులా గోధుమ రంగు మచ్చలు వచ్చేవరకు కాల్చండి.",
        "వెన్న రాసి వేడిగా వడ్డించండి.",
      ],
      hi: [
        "आटे को पानी और नमक के साथ नरम गूंथ लें।",
        "आटे को 15 मिनट के लिए रख दें।",
        "लोइयां बनाकर पतली बेलें।",
        "गरम तवे पर दोनों तरफ हल्के भूरे धब्बे आने तक सेंकें।",
        "मक्खन लगाकर गरमागरम परोसें।",
      ],
    },
    nutrition: { calories: 210, protein: 5, fat: 7, carbohydrates: 32, fiber: 4 },
    benefits: {
      en: ["Good source of carbohydrates", "Contains dietary fiber", "Pairs well with any curry"],
      te: ["మంచి కార్బోహైడ్రేట్ వనరు", "పీచు పదార్థం కలిగి ఉంటుంది", "ఏ కూరతోనైనా బాగా సరిపోతుంది"],
      hi: ["कार्बोहाइड्रेट का अच्छा स्रोत", "फाइबर से भरपूर", "किसी भी करी के साथ अच्छी लगती है"],
    },
    isPopular: false,
  },
  {
    name: { en: "Palak Paneer", te: "పాలక్ పన్నీర్", hi: "पालक पनीर" },
    description: {
      en: "Soft paneer cubes simmered in a smooth, mildly spiced spinach gravy.",
      te: "మెత్తని పాలకూర గ్రేవీలో ఉడికించిన మెత్తని పన్నీర్ ముక్కలు.",
      hi: "मुलायम पालक की ग्रेवी में पकाए गए नरम पनीर के टुकड़े।",
    },
    category: "dinner",
    foodType: "vegetarian",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Saag_Paneer.jpg",
    preparationTime: 15,
    cookingTime: 20,
    servings: 3,
    ingredients: [
      { name: { en: "Spinach", te: "పాలకూర", hi: "पालक" }, quantity: 500, unit: "g", isPantryStaple: false },
      { name: { en: "Paneer", te: "పన్నీర్", hi: "पनीर" }, quantity: 200, unit: "g", isPantryStaple: false },
      { name: { en: "Onion", te: "ఉల్లిపాయ", hi: "प्याज" }, quantity: 1, unit: "g", isPantryStaple: false },
      { name: { en: "Garlic", te: "వెల్లుల్లి", hi: "लहसुन" }, quantity: 3, unit: "g", isPantryStaple: false },
      { name: { en: "Cream", te: "క్రీమ్", hi: "क्रीम" }, quantity: 2, unit: "tbsp", isPantryStaple: false },
      { name: { en: "Turmeric", te: "పసుపు", hi: "हल्दी" }, quantity: 0.5, unit: "tsp", isPantryStaple: true },
      { name: { en: "Cooking oil", te: "వంట నూనె", hi: "खाना पकाने का तेल" }, quantity: 2, unit: "tbsp", isPantryStaple: true },
      { name: { en: "Salt", te: "ఉప్పు", hi: "नमक" }, quantity: 1, unit: "tsp", isPantryStaple: true },
    ],
    preparationSteps: {
      en: [
        "Blanch spinach in hot water for 2 minutes, then blend into a puree.",
        "Heat oil, saute onion and garlic until golden.",
        "Add the spinach puree and turmeric, simmer for 5 minutes.",
        "Add paneer cubes and salt, cook gently for 5 minutes.",
        "Stir in cream and serve hot with roti or rice.",
      ],
      te: [
        "పాలకూరను వేడి నీటిలో 2 నిమిషాలు ఉడికించి రుబ్బండి.",
        "నూనె వేడి చేసి ఉల్లిపాయ, వెల్లుల్లి బంగారు రంగు వచ్చేవరకు వేయించండి.",
        "పాలకూర రుబ్బిన మిశ్రమం, పసుపు వేసి 5 నిమిషాలు ఉడికించండి.",
        "పన్నీర్ ముక్కలు, ఉప్పు వేసి మెత్తగా 5 నిమిషాలు ఉడికించండి.",
        "క్రీమ్ కలిపి రొట్టె లేదా అన్నంతో వేడిగా వడ్డించండి.",
      ],
      hi: [
        "पालक को गरम पानी में 2 मिनट उबालकर पीस लें।",
        "तेल गरम कर प्याज और लहसुन सुनहरा होने तक भूनें।",
        "पालक की प्यूरी और हल्दी डालकर 5 मिनट पकाएं।",
        "पनीर के टुकड़े और नमक डालकर धीरे से 5 मिनट पकाएं।",
        "क्रीम मिलाकर रोटी या चावल के साथ गरमागरम परोसें।",
      ],
    },
    nutrition: { calories: 310, protein: 15, fat: 22, carbohydrates: 12, fiber: 5 },
    benefits: {
      en: ["Rich in iron from spinach", "Good source of protein and calcium", "Contains essential vitamins"],
      te: ["పాలకూర నుండి ఇనుము సమృద్ధిగా", "ప్రొటీన్, కాల్షియం మంచి వనరు", "అవసరమైన విటమిన్లు కలిగి ఉంటుంది"],
      hi: ["पालक से आयरन से भरपूर", "प्रोटीन और कैल्शियम का अच्छा स्रोत", "आवश्यक विटामिन युक्त"],
    },
    isPopular: true,
  },
  {
    name: { en: "Egg Curry", te: "గుడ్డు కూర", hi: "अंडा करी" },
    description: {
      en: "Boiled eggs simmered in a spiced onion-tomato gravy.",
      te: "మసాలా ఉల్లిపాయ-టమాటా గ్రేవీలో ఉడికించిన గుడ్లు.",
      hi: "मसालेदार प्याज-टमाटर ग्रेवी में पकाए गए उबले अंडे।",
    },
    category: "dinner",
    foodType: "non-vegetarian",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Egg_curry.jpg",
    preparationTime: 10,
    cookingTime: 20,
    servings: 2,
    ingredients: [
      { name: { en: "Egg", te: "గుడ్డు", hi: "अंडा" }, quantity: 4, unit: "g", isPantryStaple: false },
      { name: { en: "Onion", te: "ఉల్లిపాయ", hi: "प्याज" }, quantity: 2, unit: "g", isPantryStaple: false },
      { name: { en: "Tomato", te: "టమాటా", hi: "टमाटर" }, quantity: 2, unit: "g", isPantryStaple: false },
      { name: { en: "Chilli powder", te: "మిర్చి పొడి", hi: "मिर्च पाउडर" }, quantity: 1, unit: "tsp", isPantryStaple: false },
      { name: { en: "Turmeric", te: "పసుపు", hi: "हल्दी" }, quantity: 0.5, unit: "tsp", isPantryStaple: true },
      { name: { en: "Cooking oil", te: "వంట నూనె", hi: "खाना पकाने का तेल" }, quantity: 2, unit: "tbsp", isPantryStaple: true },
      { name: { en: "Salt", te: "ఉప్పు", hi: "नमक" }, quantity: 1, unit: "tsp", isPantryStaple: true },
    ],
    preparationSteps: {
      en: [
        "Boil the eggs, peel and lightly slit them.",
        "Heat oil, saute onions until golden brown.",
        "Add tomatoes, turmeric and chilli powder, cook until oil separates.",
        "Add the eggs and salt, coat well with the masala.",
        "Add a little water, simmer for 8-10 minutes and serve.",
      ],
      te: [
        "గుడ్లు ఉడికించి తొక్క తీసి కొద్దిగా చీల్చండి.",
        "నూనె వేడి చేసి ఉల్లిపాయలు బంగారు రంగు వచ్చేవరకు వేయించండి.",
        "టమాటాలు, పసుపు, మిర్చి పొడి వేసి నూనె విడిపోయేవరకు ఉడికించండి.",
        "గుడ్లు, ఉప్పు వేసి మసాలాలో బాగా కలపండి.",
        "కొద్దిగా నీరు వేసి 8-10 నిమిషాలు ఉడికించి వడ్డించండి.",
      ],
      hi: [
        "अंडे उबालकर छीलें और हल्का चीरा लगाएं।",
        "तेल गरम कर प्याज सुनहरा होने तक भूनें।",
        "टमाटर, हल्दी और मिर्च पाउडर डालकर तेल अलग होने तक पकाएं।",
        "अंडे और नमक डालकर मसाले में अच्छी तरह लपेटें।",
        "थोड़ा पानी डालकर 8-10 मिनट पकाकर परोसें।",
      ],
    },
    nutrition: { calories: 260, protein: 14, fat: 18, carbohydrates: 10, fiber: 2 },
    benefits: {
      en: ["Excellent source of protein", "Contains essential vitamins", "Supports muscle health"],
      te: ["అద్భుతమైన ప్రొటీన్ వనరు", "అవసరమైన విటమిన్లు కలిగి ఉంటుంది", "కండరాల ఆరోగ్యానికి తోడ్పడుతుంది"],
      hi: ["प्रोटीन का उत्कृष्ट स्रोत", "आवश्यक विटामिन युक्त", "मांसपेशियों के स्वास्थ्य में सहायक"],
    },
    isPopular: false,
  },
  {
    name: { en: "Fish Curry", te: "చేప కూర", hi: "मछली करी" },
    description: {
      en: "Fresh fish pieces simmered in a tangy, spiced coconut-tomato gravy.",
      te: "పులుపు, మసాలా కొబ్బరి-టమాటా గ్రేవీలో ఉడికించిన తాజా చేప ముక్కలు.",
      hi: "खट्टी, मसालेदार नारियल-टमाटर ग्रेवी में पकाए गए ताज़े मछली के टुकड़े।",
    },
    category: "dinner",
    foodType: "non-vegetarian",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Coconut_Fish_curry.jpg",
    preparationTime: 15,
    cookingTime: 25,
    servings: 3,
    ingredients: [
      { name: { en: "Fish", te: "చేప", hi: "मछली" }, quantity: 500, unit: "g", isPantryStaple: false },
      { name: { en: "Tomato", te: "టమాటా", hi: "टमाटर" }, quantity: 2, unit: "g", isPantryStaple: false },
      { name: { en: "Tamarind", te: "చింతపండు", hi: "इमली" }, quantity: 1, unit: "tbsp", isPantryStaple: false },
      { name: { en: "Coconut", te: "కొబ్బరి", hi: "नारियल" }, quantity: 0.5, unit: "cup", isPantryStaple: false },
      { name: { en: "Chilli powder", te: "మిర్చి పొడి", hi: "मिर्च पाउडर" }, quantity: 1, unit: "tsp", isPantryStaple: false },
      { name: { en: "Turmeric", te: "పసుపు", hi: "हल्दी" }, quantity: 0.5, unit: "tsp", isPantryStaple: true },
      { name: { en: "Cooking oil", te: "వంట నూనె", hi: "खाना पकाने का तेल" }, quantity: 2, unit: "tbsp", isPantryStaple: true },
      { name: { en: "Salt", te: "ఉప్పు", hi: "नमक" }, quantity: 1, unit: "tsp", isPantryStaple: true },
    ],
    preparationSteps: {
      en: [
        "Marinate fish pieces with turmeric and salt for 15 minutes.",
        "Grind coconut into a smooth paste.",
        "Heat oil, cook tomatoes and chilli powder until soft.",
        "Add the coconut paste and tamarind water, simmer for 5 minutes.",
        "Gently add the fish and cook covered for 10-12 minutes without stirring too much.",
      ],
      te: [
        "చేప ముక్కలను పసుపు, ఉప్పుతో 15 నిమిషాలు మెరినేట్ చేయండి.",
        "కొబ్బరిని మెత్తగా రుబ్బండి.",
        "నూనె వేడి చేసి టమాటాలు, మిర్చి పొడి మెత్తగా అయ్యేవరకు ఉడికించండి.",
        "కొబ్బరి పేస్ట్, చింతపండు నీరు వేసి 5 నిమిషాలు ఉడికించండి.",
        "చేప ముక్కలు మెల్లగా వేసి 10-12 నిమిషాలు మూత పెట్టి ఎక్కువగా కలపకుండా ఉడికించండి.",
      ],
      hi: [
        "मछली के टुकड़ों को हल्दी और नमक के साथ 15 मिनट मैरिनेट करें।",
        "नारियल को बारीक पीस लें।",
        "तेल गरम कर टमाटर और मिर्च पाउडर नरम होने तक पकाएं।",
        "नारियल पेस्ट और इमली का पानी डालकर 5 मिनट पकाएं।",
        "मछली धीरे से डालकर ढककर 10-12 मिनट बिना ज्यादा हिलाए पकाएं।",
      ],
    },
    nutrition: { calories: 290, protein: 24, fat: 16, carbohydrates: 8, fiber: 3 },
    benefits: {
      en: ["Rich in omega-3 fatty acids", "Excellent source of protein", "Supports heart health"],
      te: ["ఒమేగా-3 కొవ్వు ఆమ్లాలు సమృద్ధిగా", "అద్భుతమైన ప్రొటీన్ వనరు", "గుండె ఆరోగ్యానికి తోడ్పడుతుంది"],
      hi: ["ओमेगा-3 फैटी एसिड से भरपूर", "प्रोटीन का उत्कृष्ट स्रोत", "हृदय स्वास्थ्य में सहायक"],
    },
    isPopular: false,
  },
  {
    name: { en: "Vegetable Soup", te: "కూరగాయల సూప్", hi: "वेजिटेबल सूप" },
    description: {
      en: "A light, warming soup made with mixed vegetables, perfect for a simple dinner.",
      te: "కూరగాయలతో వండిన తేలికైన, వెచ్చని సూప్, సాధారణ రాత్రి భోజనానికి అనువైనది.",
      hi: "मिश्रित सब्जियों से बना हल्का, गरम सूप, सादे रात के खाने के लिए बढ़िया।",
    },
    category: "dinner",
    foodType: "vegetarian",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Vegetable_soup.jpg",
    preparationTime: 10,
    cookingTime: 20,
    servings: 2,
    ingredients: [
      { name: { en: "Carrot", te: "క్యారెట్", hi: "गाजर" }, quantity: 1, unit: "g", isPantryStaple: false },
      { name: { en: "Beans", te: "బీన్స్", hi: "बीन्स" }, quantity: 1, unit: "g", isPantryStaple: false },
      { name: { en: "Sweet corn", te: "మొక్కజొన్న", hi: "स्वीट कॉर्न" }, quantity: 0.5, unit: "cup", isPantryStaple: false },
      { name: { en: "Garlic", te: "వెల్లుల్లి", hi: "लहसुन" }, quantity: 2, unit: "g", isPantryStaple: false },
      { name: { en: "Black pepper", te: "మిరియాలు", hi: "काली मिर्च" }, quantity: 0.5, unit: "tsp", isPantryStaple: false },
      { name: { en: "Cooking oil", te: "వంట నూనె", hi: "खाना पकाने का तेल" }, quantity: 1, unit: "tbsp", isPantryStaple: true },
      { name: { en: "Water", te: "నీరు", hi: "पानी" }, quantity: 3, unit: "cup", isPantryStaple: true },
      { name: { en: "Salt", te: "ఉప్పు", hi: "नमक" }, quantity: 0.5, unit: "tsp", isPantryStaple: true },
    ],
    preparationSteps: {
      en: [
        "Finely chop all vegetables.",
        "Heat oil, saute garlic briefly.",
        "Add the vegetables and stir-fry for 2 minutes.",
        "Add water and salt, bring to a boil and simmer for 10 minutes.",
        "Season with black pepper and serve hot.",
      ],
      te: [
        "అన్ని కూరగాయలను చిన్నగా తరగండి.",
        "నూనె వేడి చేసి వెల్లుల్లిని కొద్దిగా వేయించండి.",
        "కూరగాయలు వేసి 2 నిమిషాలు వేయించండి.",
        "నీరు, ఉప్పు వేసి మరిగించి 10 నిమిషాలు ఉడికించండి.",
        "మిరియాలు వేసి వేడిగా వడ్డించండి.",
      ],
      hi: [
        "सभी सब्जियों को बारीक काटें।",
        "तेल गरम कर लहसुन को हल्का भूनें।",
        "सब्जियां डालकर 2 मिनट भूनें।",
        "पानी और नमक डालकर उबाल लें और 10 मिनट पकाएं।",
        "काली मिर्च डालकर गरमागरम परोसें।",
      ],
    },
    nutrition: { calories: 90, protein: 3, fat: 3, carbohydrates: 14, fiber: 4 },
    benefits: {
      en: ["Low in calories", "Rich in vitamins from vegetables", "Hydrating and light on the stomach"],
      te: ["తక్కువ కేలరీలు", "కూరగాయల నుండి విటమిన్లు సమృద్ధిగా", "నీటిశాతం ఎక్కువ, కడుపుకు తేలిక"],
      hi: ["कम कैलोरी", "सब्जियों से विटामिन से भरपूर", "हाइड्रेटिंग और पेट के लिए हल्का"],
    },
    isPopular: false,
  },
  {
    name: { en: "Curd Rice", te: "పెరుగు అన్నం", hi: "दही चावल" },
    description: {
      en: "Cooling rice mixed with fresh curd, tempered with mustard seeds and curry leaves.",
      te: "తాజా పెరుగుతో కలిపిన చల్లని అన్నం, ఆవాలు, కరివేపాకుతో తాలింపు వేసినది.",
      hi: "ताज़े दही में मिलाया गया ठंडा चावल, राई और करी पत्ते के तड़के के साथ।",
    },
    category: "pantry",
    foodType: "vegetarian",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Curd_Rice.jpg",
    preparationTime: 5,
    cookingTime: 10,
    servings: 2,
    ingredients: [
      { name: { en: "Rice", te: "బియ్యం", hi: "चावल" }, quantity: 1, unit: "cup", isPantryStaple: false },
      { name: { en: "Curd", te: "పెరుగు", hi: "दही" }, quantity: 1, unit: "cup", isPantryStaple: false },
      { name: { en: "Mustard seeds", te: "ఆవాలు", hi: "राई" }, quantity: 1, unit: "tsp", isPantryStaple: false },
      { name: { en: "Curry leaves", te: "కరివేపాకు", hi: "करी पत्ता" }, quantity: 8, unit: "g", isPantryStaple: false },
      { name: { en: "Cooking oil", te: "వంట నూనె", hi: "खाना पकाने का तेल" }, quantity: 1, unit: "tbsp", isPantryStaple: true },
      { name: { en: "Salt", te: "ఉప్పు", hi: "नमक" }, quantity: 0.5, unit: "tsp", isPantryStaple: true },
    ],
    preparationSteps: {
      en: [
        "Cook the rice soft and let it cool slightly.",
        "Mash the rice lightly and mix in the curd and salt.",
        "Heat oil, splutter mustard seeds and curry leaves.",
        "Pour the tempering over the curd rice and mix well.",
        "Refrigerate briefly and serve cool.",
      ],
      te: [
        "అన్నం మెత్తగా వండి కొద్దిగా చల్లారనివ్వండి.",
        "అన్నం కొద్దిగా నలగ్గొట్టి పెరుగు, ఉప్పు కలపండి.",
        "నూనె వేడి చేసి ఆవాలు, కరివేపాకు తాలింపు వేయండి.",
        "తాలింపును పెరుగు అన్నంపై పోసి బాగా కలపండి.",
        "కొద్దిసేపు చల్లబరిచి చల్లగా వడ్డించండి.",
      ],
      hi: [
        "चावल को नरम पकाकर थोड़ा ठंडा होने दें।",
        "चावल को हल्का मैश करें और दही व नमक मिलाएं।",
        "तेल गरम कर राई और करी पत्ते का तड़का लगाएं।",
        "तड़के को दही चावल पर डालकर अच्छी तरह मिलाएं।",
        "थोड़ी देर ठंडा कर ठंडा ही परोसें।",
      ],
    },
    nutrition: { calories: 220, protein: 6, fat: 5, carbohydrates: 38, fiber: 1 },
    benefits: {
      en: ["Good for digestion", "Cooling and light", "Contains probiotics from curd"],
      te: ["జీర్ణక్రియకు మంచిది", "చల్లగా, తేలికగా ఉంటుంది", "పెరుగు నుండి ప్రొబయోటిక్స్"],
      hi: ["पाचन के लिए अच्छा", "ठंडा और हल्का", "दही से प्रोबायोटिक्स"],
    },
    isPopular: false,
  },
  {
    name: { en: "Vegetable Khichdi", te: "కూరగాయల ఖిచిడీ", hi: "वेजिटेबल खिचड़ी" },
    description: {
      en: "A one-pot comfort meal of rice and lentils cooked with mixed vegetables.",
      te: "కూరగాయలతో వండిన బియ్యం, పప్పు కలిపిన ఒకే పాత్రలో వండే తృప్తికరమైన భోజనం.",
      hi: "मिश्रित सब्जियों के साथ पकाया गया चावल और दाल का एक-बर्तन आरामदायक भोजन।",
    },
    category: "pantry",
    foodType: "vegetarian",
    image: "https://commons.wikimedia.org/wiki/Special:FilePath/Khichdi_with_papad.jpg",
    preparationTime: 10,
    cookingTime: 25,
    servings: 3,
    ingredients: [
      { name: { en: "Rice", te: "బియ్యం", hi: "चावल" }, quantity: 1, unit: "cup", isPantryStaple: false },
      { name: { en: "Moong dal", te: "పెసరపప్పు", hi: "मूंग दाल" }, quantity: 0.5, unit: "cup", isPantryStaple: false },
      { name: { en: "Carrot", te: "క్యారెట్", hi: "गाजर" }, quantity: 1, unit: "g", isPantryStaple: false },
      { name: { en: "Beans", te: "బీన్స్", hi: "बीन्स" }, quantity: 1, unit: "g", isPantryStaple: false },
      { name: { en: "Turmeric", te: "పసుపు", hi: "हल्दी" }, quantity: 0.5, unit: "tsp", isPantryStaple: true },
      { name: { en: "Ghee", te: "నెయ్యి", hi: "घी" }, quantity: 2, unit: "tbsp", isPantryStaple: true },
      { name: { en: "Water", te: "నీరు", hi: "पानी" }, quantity: 4, unit: "cup", isPantryStaple: true },
      { name: { en: "Salt", te: "ఉప్పు", hi: "नमक" }, quantity: 1, unit: "tsp", isPantryStaple: true },
    ],
    preparationSteps: {
      en: [
        "Wash rice and moong dal together.",
        "Chop the vegetables into small pieces.",
        "Pressure cook rice, dal, vegetables, turmeric and salt with water until soft and mushy.",
        "Mash lightly to the desired consistency.",
        "Top with a spoon of ghee and serve hot.",
      ],
      te: [
        "బియ్యం, పెసరపప్పును కలిపి కడగండి.",
        "కూరగాయలను చిన్న ముక్కలుగా కోయండి.",
        "బియ్యం, పప్పు, కూరగాయలు, పసుపు, ఉప్పుతో నీరు వేసి మెత్తగా అయ్యేవరకు ప్రెజర్ కుక్ చేయండి.",
        "కావలసిన చిక్కదనానికి కొద్దిగా నలగ్గొట్టండి.",
        "నెయ్యి వేసి వేడిగా వడ్డించండి.",
      ],
      hi: [
        "चावल और मूंग दाल को साथ धो लें।",
        "सब्जियों को छोटे टुकड़ों में काटें।",
        "चावल, दाल, सब्जियां, हल्दी, नमक और पानी डालकर नरम होने तक प्रेशर कुक करें।",
        "मनचाही स्थिरता के लिए हल्का मैश करें।",
        "ऊपर से घी डालकर गरमागरम परोसें।",
      ],
    },
    nutrition: { calories: 250, protein: 9, fat: 7, carbohydrates: 38, fiber: 5 },
    benefits: {
      en: ["Easy to digest", "Balanced source of protein and carbohydrates", "Comforting one-pot meal"],
      te: ["సులభంగా జీర్ణమవుతుంది", "ప్రొటీన్, కార్బోహైడ్రేట్ సమతుల్యంగా ఉంటుంది", "తృప్తినిచ్చే ఒకే పాత్ర భోజనం"],
      hi: ["आसानी से पचने वाला", "प्रोटीन और कार्बोहाइड्रेट का संतुलित स्रोत", "आरामदायक एक-बर्तन भोजन"],
    },
    isPopular: false,
  },
];
